### ISSUE TITLE
Error message running Training

### ISSUE THREAD

**Issue by usalexsantos** [eti-p-doray/unet-gan-matting#20]
I'm getting an error message when running the Training.

C:\unet-gan-matting-master>python train.py scripts/data
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from script import resize
ModuleNotFoundError: No module named 'script'

Am I missing something?

**Comment by y0un35** [comment]
I've the same issue! also the folder data is in the principal path not inside the folder scripts !

**Comment by Am1n3e** [comment]
@usalexsantos @y0un35  thanks for notifying us. I have fixed the issue.
Also, I was not able to try it to see if there is other issue. Can you try it, if it does not solve the issue you can re-open this ticket.

**Comment by usalexsantos** [comment]
@aminHatim 

This is the issue I get now with the new file.

C:\unet-gan-matting-master>python train.py scripts/data
Traceback (most recent call last):
  File "train.py", line 226, in <module>
    main(args)
  File "train.py", line 69, in main
    ids = [[int(i) for i in os.path.splitext(filename)[0].split('_')] for filename in os.listdir(input_path)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'scripts/data\\input'

**Comment by Am1n3e** [comment]
@usalexsantos  I see you issue you are running it on windows that is why the path is mess up `/` vs `\`. I will see what I can do, but can't promise any thing, unless you want to do a pull request.

**Comment by sanishan** [comment]
> @aminHatim
> 
> This is the issue I get now with the new file.
> 
> C:\unet-gan-matting-master>python train.py scripts/data
> Traceback (most recent call last):
> File "train.py", line 226, in 
> main(args)
> File "train.py", line 69, in main
> ids = [[int(i) for i in os.path.splitext(filename)[0].split('_')] for filename in os.listdir(input_path)]
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'scripts/data\input'

Same issue on CentOs

**Comment by shreshthasarkar** [comment]
just change it / to \ the problem would be solved.
