### ISSUE TITLE
An error occurred while running the evaluation script

### ISSUE THREAD

**Issue by xuanhan863** [eti-p-doray/unet-gan-matting#21]
When I run the evaluation script
with: 
python3 eval.py data/matting/input/107_0.jpg  data/matting/trimap/107_trimap.jpg result.jpg --checkpoint -1

An IndexError occurs on eval.py line 48 : alpha = cv2.split(foreground)[3]

**Comment by afaq-ahmad** [comment]
Hi xuanhan863, facing the same issue, did you found any solution?

**Comment by antithing** [comment]
Same here! Did either of you find a solution for this?

**Comment by afaq-ahmad** [comment]
python3 eval.py ./unet-gan-matting-master/scripts/data/input/0_0.jpg ./unet-gan-matting-master/scripts/data/matting/target/0.png ./unet-gan-matting-master/scripts/data/output --checkpoint -1

this gives some results

**Comment by julesd16** [comment]
Hello! 
alpha = cv2.split(foreground)[3] change to alpha = cv2.split(foreground)[2].

**Comment by theadventureoflinko** [comment]
It seems that trimap image has to be an image which have an alpha channel.
In my case, my trimap is a grayscale image, so I changed
```
alpha = cv2.split(foreground)[3]
```
to
```
alpha = foreground
```

I'm not sure that it is correct way, because output image is still not clean.
